module.exports = [
  ["", "luobinjie2017@gmail.com "],
  ["", "lam.lindamckeith@gmail.com"],
  ["", "stephani.kell@gmail.com"],
  ["", "michaelw.kcs@gmail.com"],
  ["", "davidyoon85@gmail.com"],
  ["", "lytton.liao@gmail.com"],
  ["", "gmrempe@gmail.com"],
  ["", "lutherye@gmail.com"],
  ["", "georgeliu96@gmail.com"],
  ["", "wellingtonfragoso2@gmail.com"],
  ["", "omar.work2@gmail.com"],
  ["", "anneliynv@gmail.com"],
  ["", "dan.noh@gmail.com"],
  ["", "danteacantal@gmail.com"],
  ["", "grahamgjohnson@gmail.com"],
  ["", "hcheon549@gmail.com"],
  ["", "jason@jmbourgoin.com"],
  ["", "jgdarmoni@gmail.com"],
  ["", "maxtrukhin@gmail.com"],
  ["", "mcavini@outlook.com"],
  ["", "rainrues@gmail.com"],
  ["", "samhudisnyc@gmail.com"],
  ["", "lucasfschraier@gmail.com"],
  ["", "raymond_munoz@alumni.brown.edu"],
  ["", "tbisson11@gmail.com"],
  ["", "myron.yook@gmail.com"],
  ["", "urosh.stojkovikj@gmail.com"],
  ["", "lukewhchen@gmail.com"],
  ["", "stephen.li305@gmail.com"],
];
