module.exports = [
  ["Gabriel", "gflujan@gmail.com"],
  ["Ivan", "ivan.kwong710@gmail.com"],
  ["Ryan", "ryanfoong8983@gmail.com"],
  ["Sam", "sam.d.odonnell@gmail.com"],
  ["Josh", "joshuachoi0508@gmail.com"],
  ["Dennis", "dmyasnyankin@berkeley.edu"],
  ["Taran", "tarancacacho@gmail.com"],
  ["Ben", "benjcowden@gmail.com"],
  ["Rome", "romebell5@gmail.com"],
  ["Michael", "michaelvaleriani@gmail.com"],
  ["Brian", "brianiswinston@yahoo.com"],
  ["Rewel", "rgjr22@gmail.com"],
  ["Jason", "wongcjason@gmail.com"],
  ["Vanessa", "vanchen07@gmail.com"],
  ["Jaya", "jayal2905@gmail.com"],
  ["Rika", "ruijiasun1323@gmail.com"],
  ["Farah", "fyquader@gmail.com"],
  ["Melvin", "mtmallari@ucdavis.edu"],
  ["Niya", "niyatihd@gmail.com"],
  ["Robin", "robintsunny@gmail.com"]
];
