module.exports = [
  // ["Alex", "alexg62288@gmail.com"],
  // ["Bryan", "lin.bry@gmail.com"],
  ["Nadav", "nadavnoy@yahoo.com"],
  ["Richard", "rich.maaa@gmail.com"],
  ["Franklin", "franklinchang4695@gmail.com"],
  ["Ali", "alialkaheli1@gmail.com"],
  ["Nicholas", "howlett@uchicago.edu"],
  // ["Hong", "hongyang.gao@gmail.com"],
  ["Craig", "craig9907@gmail.com"],
  ["Andrew", "andrew.engelstein@gmail.com"],
  ["Tamir", "tkarssli@gmail.com"],
  ["Michael", "michaelcgee93@gmail.com"],
  // ["Stefanie", "luu.stefanie@gmail.com"],
  ["Darren", "contact.darrenyong@gmail.com"],
  ["Jorge", "jopa46@gmail.com"],
  // ["Nathasha", "nathasha36@gmail.com"],
  ["Jason", "jasonfu1992@gmail.com"],
  ["Corinne", "c.m.hickey06@gmail.com"],
  ["Grady", "gradyzhoo@gmail.com"],
  // ["Dirk", "cornelis.dirk.haupt@gmail.com"]
];
